name: conda_metabolic_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.23
  - bwa=0.7.19
  - diamond=2.1.13
  - hmmer=3.4
  - htslib=1.22.1
  - samtools=1.22.1
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.13.1
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - statsmodels=0.14.5
  - pip=25.2
  - setuptools=80.9.0
  - wheel=0.45.1
  - requests=2.32.5
  - aiohttp=3.12.15
  - boto3=1.40.13
  - google-cloud-storage=3.3.0
  - google-api-python-client=2.179.0
  - dropbox=12.0.2
  - pyyaml=6.0.2
  - jsonschema=4.25.1
  - configargparse=1.5.3
  - tabulate=0.9.0
  - prettytable=3.16.0
  - pulp=2.7.0
  - toposort=1.10
  - gitpython=3.1.45
  - psutil=5.9.5
  - tqdm=4.65.0
  - throttler=1.2.2
  - smart_open=7.3.0
  - ftputil=5.1.0
  - pysftp=0.2.9
  - python-irodsclient=3.1.1
  - aioeasywebdav=2.4.0
  - filechunkio=1.8
  - datrie=0.8.2
  - dpath=2.2.0
  - appdirs=1.4.4
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - humanfriendly=10.0
  - plac=1.4.5
  - stopit=1.1.2
  - connection_pool=0.0.3
  - reretry=0.11.8
  - yte=1.8.1
  - peppy=0.40.7
  - pephubclient=0.4.4
  - eido=0.2.4
  - ubiquerg=0.8.0
  - logmuse=0.2.8
  - veracitools=0.1.3
  - cryptography=45.0.6
  - bcrypt=4.3.0
  - paramiko=4.0.0
  - pynacl=1.5.0
  - pyopenssl=25.1.0
  - pyqt=5.15.11
  - qt-main=5.15.15
  - coin-or-cbc=2.10.12
  - coincbc=2.10.12
  - pulp=2.7.0
  - graphviz=8.0.5
  - pillow=11.3.0
  - contourpy=1.3.0
  - fonttools=4.59.1
  - pydantic=2.11.7
  - typing-extensions=4.14.1
  - attrs=25.3.0
  - pytest=8.4.1
  - click=8.1.8
  - typer=0.16.1
  - invoke=2.2.0
  - shellingham=1.5.4
  - rich=14.1.0
  - docutils=0.22
  - pygments=2.19.2
  - markdown-it-py=3.0.0
  - jinja2=3.1.2
  - nbformat=5.10.4
  - jupyter_core=5.8.1
  - toml=0.10.2
  - tomli=2.2.1
  - six=1.17.0
  - wcwidth=0.2.13
  - zipp=3.23.0
  - importlib-resources=6.5.2
  - platformdirs=4.3.8
  - packaging=25.0
  - pyparsing=3.2.3
  - python-dateutil=2.9.0.post0
  - pytz=2025.2
  - tzdata=2025b
  - certifi=2025.8.3
  - ca-certificates=2025.8.3
  - idna=3.10
  - charset-normalizer=3.4.3
  - urllib3=1.26.19
  - mpi=1.0
  - openmpi=4.1.6
  - wget=1.21.4
  - curl=8.14.1
  - perl=5.32.1
  - pip:
    - biopython==1.81